- hosts: web
  roles:
    - install_nginx
    - install_uwsgi
    - deploy_app
    - setup_nginx

- hosts: lb
  roles:
    - install_haproxy
    - setup_haproxy

- hosts: all
  roles:
    - setup_unattended_upgrades
